default:
  image: docker

services:
  - docker:dind

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/cache/

variables:
  DOCKER_DRIVER: overlay2

include:
  - '/gitlab-ci/build/steps.yml'
  - '/gitlab-ci/test/steps.yml'
  - '/gitlab-ci/deploy/steps.yml'

stages:
  - Build
  - Test
  - Deploy

### Environments ###
.environment_prod:
  only:
    - main
  environment: 
    name: prod

.environment_staging:
  only:
    - staging
  environment: 
    name: staging

.environment_dev:
  only:
    - dev
  environment:
    name: dev
    
.environment_mr:
  only:
    - merge_requests
  environment:
    name: dev/$CI_COMMIT_REF_NAME