import type { ReactNode } from 'react';
import type { Metadata } from 'next';
import Providers from '@/app/providers';
import { Footer } from '@/components/footer';
import { Header } from '@/components/header';
import './globals.css';

export const metadata: Metadata = {
  title: 'ALDI Deals Frontend',
  description: 'Generated by create next app',
};

export interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="de">
      <body>
        <Header />
        <main>
          <div>
            <Providers>{children}</Providers>
          </div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
