.deploy_application:
  when: on_success
  stage: Deploy
  script:
    - apk add --no-cache curl
    - curl -LO $KUBECTL_TOOL_URL
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - docker info
    - docker --version
    - kubectl version --client
    - curl -LO $KUBECTL_AZURE_TOOL
    - unzip kubelogin-linux-amd64.zip
    - chmod +x ./bin/linux_amd64/kubelogin
    - mv ./bin/linux_amd64/kubelogin /usr/local/bin/kubelogin
    #- kubelogin convert-kubeconfig -l spn
    - kubectl config get-contexts
    - kubectl config use-context $KUBE_CONTEXT
    - kubectl --kubeconfig ${KUBECONFIG} rollout restart deploy $IMAGE_NAME -n $CI_ENVIRONMENT_NAME

deploy_application_prod:
  extends:
    - .deploy_application
    - .environment_prod
  before_script:
    - export KUBECONFIG=$PROD_KUBECONFIG

deploy_application_staging:
  extends:
    - .deploy_application
    - .environment_staging
  before_script:
    - export KUBECONFIG=$STAGING_KUBECONFIG

deploy_application_dev:
  extends:
    - .deploy_application
    - .environment_dev
  before_script:
    - export KUBECONFIG=$DEV_KUBECONFIG
